name: flutter_application_6
description: Internationalization in flutter with supporting multiple language

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  after_layout: ^1.1.0
  curved_navigation_bar: ^1.0.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^9.2.0
  introduction_screen: ^2.1.0  
  shared_preferences: ^2.0.13
  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.1
  carousel_slider: ^4.0.0
  line_icons: ^2.0.0
  direct_select: ^2.0.0
  hexcolor: ^2.0.7
  flutter_svg: ^1.0.3
  image_picker: ^0.8.5+3
  convex_bottom_bar: ^3.0.0
  flutter_phone_direct_caller: ^2.1.1
  smooth_page_indicator: ^1.0.0+2
  url_launcher: ^6.1.2
  google_maps_flutter: ^2.0.9
  location: ^4.4.0
  geocoding: ^2.0.4

  

dev_dependencies:
  flutter_test:
    sdk: flutter

  #shared_preferences: ^0.5.7+3
  


flutter:

  uses-material-design: true

  assets:
    - assets/1.png
    - assets/2.png
    - assets/logoImran.png
    - assets/introscreen1.png
    - assets/introscreen2.png
    - assets/introscreen3.png
    - assets/introscreen4.png
    - assets/Group 3 (3).png
    - assets/img.png
    - assets/logoImran.png
    - assets/image_maison.webp
    
    - assets/inscription.png
    - assets/play.png
    - assets/Group 4 (6).png
    - assets/Group-1-3-Co.png
    - assets/Group 4 (6).png
    - assets/pana.png
    - assets/Group 3.png
    - assets/Ellipse 1.png
    - assets/imran_blue.svg
    - assets/pana.svg
    - assets/logo+imran_blue.svg
    - assets/logo+imran_white.svg
    - assets/map_img.png
    - assets/imran agence.svg
    - assets/img_top.png
    - assets/top_bar.png
    - assets/top_bar_agence.png
    - assets/Imran.png
    - assets/Imran_client.png
    